/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vyetqiczoggxnaezybdw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5ZXRxaWN6b2dneG5hZXp5YmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNzU5ODUsImV4cCI6MjA5MTk1MTk4NX0.YVptjVs5SkqX21RSIVY9hAiVv7r_Y-NlvVZSdI0GW-A"